### ISSUE TITLE
Area Model Introduction master checklist

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-introduction#1]
## Design
- [x] **Sim folder and design doc created** (Date: 06/28/2017) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Sim suggestions doc reviewed**
- [x] **Learning goals and standards identified** (Date: 06/30/2017)
- [x] **Design concept complete**  (Date: 01/11/2018)
- [x] **Wireframes complete** (Date: 01/11/2018) 
- [x] **Mockups complete** (Date: 01/26/2018) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion** N/A
- [x] **Interviews complete** (Date: 02/16/2018) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 02/20/2018) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [x] Add an activity
  - [x] Sim primer draft
- [x] **Post-publication items** 
  - [x] Sim primer (create issue, publish ideally within 1 month of live sim)

## Implementation
- [x] **Repository created** (Date: 01/12/2018)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos (then `grunt generate-data` in perennial and check in)
- [x] **Development started** (Date: 01/12/2018)
- [x] **Sim is "feature complete"** (Date: 01/12/2018)
- [x] **Code review completed** (Date: 06/29/2018) 
- [x] **Pre-publication items** 
  - [x] Main screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Verify credits
- [x] **Published** (Date: 4/24/2018) 
  - [x] README.md updated using `grunt published-README` (in master and release branch)
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
 
## QA
- [x] **Dev testing started** (Date: 02/23/2018) 
- [x] **Dev testing completed** (Date: 03/05/2018) 
- [x] **First RC published** (Date: 04/20/2018)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 04/24/2018)
